---
- name: Install openshift-origin repo
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - centos-release-openshift-origin

- name: Install required packages
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - wget 
    - git 
    - net-tools 
    - bind-utils 
    - iptables-services 
    - bridge-utils 
    - bash-completion 
    - docker
    - origin-clients

- name: Configure docker
  replace:
    path: /etc/sysconfig/docker
    regexp: '^OPTIONS.*'
    replace: 'OPTIONS="--selinux-enabled --insecure-registry 172.30.0.0/16"'
  notify: restart docker

- name: Start docker
  systemd:
    enabled: yes
    state: started
    name: docker

- name: Open firwall ports
  firewalld:
    port: "{{ item }}"
    permanent: true
    state: enabled
  with_items:
    - 8443/tcp
    - 53/udp
    - 8053/udp

- name: Create firewall zone dockerc
  firewalld:
    zone: dockerc
    state: present
    permanent: true



- name: Configure firewall for dockerc zone
  firewalld:
    permanent: true
    zone: dockerc
    source: 172.17.0.0/16
    state: enabled
    port: "{{ item }}"
  with_items:
    - 8443/tcp
    - 53/udp
    - 8053/udp

